# Generated by Django 3.1.7 on 2021-03-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('link', models.URLField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('amount_of_upvotes', models.IntegerField(default=0)),
                ('author_name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
    ]
